language: minimal

os:
    - linux
    - osx

env:
  global:
    - CONDA_ENV=travisci_test
  matrix:
    - PYTHON_SPEC="python=3" NUMPY_SPEC="numpy" NUMBA_SPEC="numba"
    - PYTHON_SPEC="python=3" NUMPY_SPEC="numpy" NUMBA_SPEC=""
    - PYTHON_SPEC="python=2" NUMPY_SPEC="numpy" NUMBA_SPEC="numba"
    - PYTHON_SPEC="python=2" NUMPY_SPEC="numpy" NUMBA_SPEC=""

branches:
    only:
        - master

before_install:
    - export PATH=$HOME/miniconda3/bin:$PATH
    - build-scripts/travis-ci-setup.sh

script:
    - build-scripts/travis-ci-test.sh


