language: python

os:
    - linux
    - osx

env:
    - PYTHON_SPEC="python=3" NUMPY_SPEC="numpy" NUMBA_SPEC="numba"
    - PYTHON_SPEC="python=3" NUMPY_SPEC="numpy" NUMBA_SPEC=""
    - PYTHON_SPEC="python=2" NUMPY_SPEC="numpy" NUMBA_SPEC="numba"
    - PYTHON_SPEC="python=2" NUMPY_SPEC="numpy" NUMBA_SPEC=""

branches:
    only:
        - master

before_install:
    build-scripts/travis-ci-setup.sh

script:
    make test


