# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.dev0+gc6f2b48.d20230124'
__version_tuple__ = version_tuple = (0, 2, 'dev0', 'gc6f2b48.d20230124')
